const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0'),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m},time=m=>`${pad(Math.floor(m/60)%24)}:${pad(m%60)}`;
let data={},groups=[{name:'할 일',color:'blue'}],selected=new Date(),editing=null,dragId=null,lastFocus=null;
selected.setHours(0,0,0,0);
try{data=JSON.parse(localStorage.getItem('myday-v1')||'{}')||{};groups=JSON.parse(localStorage.getItem('myday-groups-v1')||'null')||groups}catch(e){showStatus('저장 데이터를 읽지 못했습니다. 백업 후 확인해 주세요.');}
// Replace the previous unused study default without changing user-created content.
if(groups.some(g=>g.name==='학습')&&!Object.values(data).some(day=>Array.isArray(day)&&day.some(ev=>ev.category==='학습'))){groups=groups.map(g=>g.name==='학습'?{...g,name:'할 일'}:g)}
const items=()=>Array.isArray(data[key(selected)])?data[key(selected)]:[];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showStatus(message){$('status').textContent=message;$('status').style.display='block';setTimeout(()=>$('status').style.display='none',3500)}
function persist(){try{localStorage.setItem('myday-v1',JSON.stringify(data));localStorage.setItem('myday-groups-v1',JSON.stringify(groups));return true}catch(e){showStatus('저장 공간이 부족합니다. 백업을 내려받아 주세요.');return false}}
function allGroups(){const names=new Set(groups.map(g=>g.name));const result=groups.slice();for(const ev of items()){const name=ev.category||'일정';if(!names.has(name)){result.push({name,color:ev.color||'blue'});names.add(name)}}return result}
function render(){const weekdays=['일','월','화','수','목','금','토'];$('date-label').textContent=`${selected.getMonth()+1}월 ${selected.getDate()}일 (${weekdays[selected.getDay()]})`;$('date').value=key(selected);renderGroups();renderTimeline()}
function renderGroups(){const root=$('groups');root.innerHTML='';for(const group of allGroups()){const list=items().filter(ev=>(ev.category||'일정')===group.name);const card=document.createElement('article');card.className='group';card.innerHTML=`<div class="group-head"><span class="dot" style="background:var(--${esc(group.color)})"></span><span class="group-name">${esc(group.name)}</span><span class="count">${list.filter(x=>x.done).length}/${list.length}</span><button class="collapse" aria-label="${esc(group.name)} 접기" aria-expanded="true">⌃</button></div><div class="task-list"></div><button class="group-plus" aria-label="${esc(group.name)} 할 일 추가">＋</button>`;const taskList=card.querySelector('.task-list');for(const ev of list){const row=document.createElement('div');row.className='task-row'+(ev.done?' completed':'');row.draggable=true;row.innerHTML=`<input class="check" type="checkbox" ${ev.done?'checked':''} aria-label="${esc(ev.task)} 완료"><button class="task-text">${esc(ev.task)}</button><button class="handle" title="드래그하여 순서 변경 · 클릭하여 수정" aria-label="${esc(ev.task)} 수정">⠿</button>`;row.querySelector('.check').onchange=e=>{ev.done=e.target.checked;persist();render()};row.querySelector('.task-text').onclick=()=>openEditor(ev.id);row.querySelector('.handle').onclick=()=>openEditor(ev.id);row.ondragstart=e=>{dragId=ev.id;e.dataTransfer.setData('text/plain',ev.id);row.classList.add('dragging')};row.ondragend=()=>{dragId=null;row.classList.remove('dragging')};row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();if(!dragId||dragId===ev.id)return;const list=items(),from=list.findIndex(x=>x.id===dragId);if(from<0)return;const [moving]=list.splice(from,1);moving.category=group.name;list.splice(list.findIndex(x=>x.id===ev.id),0,moving);persist();render()};taskList.append(row)}if(!list.length)taskList.innerHTML='<p class="empty">할 일을 추가하세요.</p>';card.querySelector('.group-plus').onclick=()=>openEditor(null,null,group.name);card.querySelector('.collapse').onclick=e=>{const expanded=e.currentTarget.getAttribute('aria-expanded')==='true';e.currentTarget.setAttribute('aria-expanded',String(!expanded));e.currentTarget.textContent=expanded?'⌄':'⌃';taskList.hidden=expanded};root.append(card)}}
function range(ev){if(!ev.start||!ev.end)return null;let s=mins(ev.start),e=mins(ev.end);if(s<5*60)s+=1440;if(e<5*60)e+=1440;if(e<=s)e+=1440;return [s,e]}
function renderTimeline(){const tl=$('timeline');tl.innerHTML='';const now=new Date(),isToday=key(now)===key(selected);for(let h=5;h<29;h++){const row=document.createElement('div');row.className='hour';const cells=document.createElement('div');cells.className='cells';for(let j=0;j<6;j++){const slot=document.createElement('button');slot.className='slot';slot.style.left=`${j/6*100}%`;slot.setAttribute('aria-label',`${time(h*60+j*10)} 일정 추가`);slot.onclick=()=>openEditor(null,h*60+j*10,'일정');cells.append(slot)}const matching=items().filter(ev=>{const r=range(ev);return r&&r[1]>h*60&&r[0]<(h+1)*60});const lanes=[];for(const ev of matching){const [s,e]=range(ev),a=Math.max(s,h*60),b=Math.min(e,(h+1)*60);let lane=lanes.findIndex(end=>end<=a);if(lane<0)lane=lanes.length;lanes[lane]=b;const block=document.createElement('button');block.className='event'+(ev.done?' done':'');block.style.background=`var(--${['blue','yellow','green','purple','orange','pink'].includes(ev.color)?ev.color:'blue'})`;block.style.left=`${(a-h*60)/60*100}%`;block.style.width=`${(b-a)/60*100}%`;block.dataset.lane=lane;block.textContent=ev.task;block.title=`${ev.task} · ${ev.start}–${ev.end}`;block.setAttribute('aria-label',block.title);block.onclick=()=>openEditor(ev.id);cells.append(block)}if(lanes.length>1){cells.querySelectorAll('.event').forEach(el=>{el.style.top=`calc(3px + (var(--row-height) - 6px) / ${lanes.length} * ${Number(el.dataset.lane)})`;el.style.height=`calc((var(--row-height) - 6px) / ${lanes.length})`;el.style.lineHeight='1';el.style.fontSize='10px';el.style.padding='1px 3px'})}const label=document.createElement('div');const clockHour=h%24,dayForRow=new Date(selected);dayForRow.setDate(dayForRow.getDate()+(h>=24?1:0));const isCurrent=key(dayForRow)===key(now)&&clockHour===now.getHours();label.className='label'+(clockHour===12?' noon':'')+(isCurrent?' now':'');label.innerHTML=`<span>${clockHour}</span>`;label.setAttribute('aria-label',`${h>=24?'다음 날 ':''}${clockHour}시`);if(isCurrent){const line=document.createElement('i');line.className='now-marker';line.style.left=`${now.getMinutes()/60*100}%`;cells.append(line)}row.append(label,cells);tl.append(row)}}
function openEditor(id=null,minute=null,category='할 일'){lastFocus=document.activeElement;editing=id;const ev=items().find(x=>x.id===id);$('editor-title').textContent=ev?'할 일 수정':'할 일 추가';$('task').value=ev?.task||'';const options=allGroups();if(!options.some(g=>g.name===category))options.push({name:category,color:'blue'});$('category').innerHTML=options.map(g=>`<option>${esc(g.name)}</option>`).join('');$('category').value=ev?.category||(ev?'일정':category);$('scheduled').checked=!!ev?.start||minute!==null;$('start').value=ev?.start||time(minute??900);$('end').value=ev?.end||time((minute??900)+30);$('memo').value=ev?.memo||'';$('color').value=ev?.color||options.find(g=>g.name===category)?.color||'blue';$('done').checked=!!ev?.done;$('delete').hidden=!ev;$('error').textContent='';updateTimeFields();$('editor').showModal();$('task').focus()}
function updateTimeFields(){document.querySelector('.time-fields').hidden=!$('scheduled').checked;$('start').required=$('end').required=$('scheduled').checked}
function closeEditor(){$('editor').close();lastFocus?.focus()}
$('scheduled').onchange=updateTimeFields;$('cancel').onclick=closeEditor;
$('form').onsubmit=e=>{e.preventDefault();const task=$('task').value.trim();if(!task){$('task').focus();return}const scheduled=$('scheduled').checked,start=scheduled?$('start').value:null,end=scheduled?$('end').value:null;if(scheduled&&(!start||!end||start===end)){ $('error').textContent='시작과 종료 시간을 다르게 입력하세요.';return}const candidate={task,start,end,category:$('category').value,color:$('color').value,memo:$('memo').value.trim(),done:$('done').checked};const span=range(candidate);if(span&&(span[0]<300||span[1]>1740)){ $('error').textContent='시간표 범위는 오전 5시부터 다음 날 오전 5시 전까지입니다.';return}if(!Array.isArray(data[key(selected)]))data[key(selected)]=[];const ev=items().find(x=>x.id===editing);if(ev)Object.assign(ev,candidate);else items().push({...candidate,id:crypto.randomUUID()});if(persist()){closeEditor();render()}};
$('delete').onclick=()=>{data[key(selected)]=items().filter(x=>x.id!==editing);if(persist()){closeEditor();render()}};
function moveDay(n){selected.setDate(selected.getDate()+n);render()}
$('previous').onclick=()=>moveDay(-1);$('next').onclick=()=>moveDay(1);$('today').onclick=()=>{selected=new Date();selected.setHours(0,0,0,0);render()};$('date-label').onclick=()=>{if($('date').showPicker)$('date').showPicker();else $('date').focus()};$('date').onchange=()=>{if($('date').value){selected=new Date($('date').value+'T00:00:00');render()}};
$('add-event').onclick=()=>openEditor(null,900,'일정');function addGroup(){$('group-name').value='';$('group-editor').showModal()};$('new-group').onclick=$('group-add').onclick=addGroup;$('group-cancel').onclick=()=>$('group-editor').close();$('group-form').onsubmit=e=>{e.preventDefault();const name=$('group-name').value.trim();if(!name)return;if(allGroups().some(g=>g.name===name)){$('group-name').setCustomValidity('이미 있는 분류입니다.');$('group-name').reportValidity();return}groups.push({name,color:$('group-color').value});persist();$('group-editor').close();render()};$('group-name').oninput=()=>$('group-name').setCustomValidity('');
$('schedule-tab').onclick=()=>{document.querySelector('main').classList.add('schedule-only');$('study-tab').classList.remove('selected');$('schedule-tab').classList.add('selected');$('schedule-tab').textContent='▦ 시간표만';document.querySelector('.study').style.display='block';document.querySelector('.study').style.minHeight='0';$('groups').hidden=true;$('group-add').hidden=true};$('study-tab').onclick=()=>{document.querySelector('main').classList.remove('schedule-only');document.querySelector('.study').style.display='';document.querySelector('.study').style.minHeight='';$('groups').hidden=false;$('group-add').hidden=false;$('study-tab').classList.add('selected');$('schedule-tab').classList.remove('selected');$('schedule-tab').textContent='▦ 시간표만'};
$('backup').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({data,groups},null,2)],{type:'application/json'}));a.download=`myDay-${key(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
let registration;let updatePending=false;
if('serviceWorker' in navigator){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!updatePending){updatePending=true;if(!$('editor').open&&!$('group-editor').open)location.reload();else showStatus('새 버전이 준비되었습니다. 편집을 마치면 업데이트됩니다.')}});for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('close',()=>{if(updatePending&&!$('editor').open&&!$('group-editor').open)location.reload()});addEventListener('load',async()=>{try{registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await registration.update()}catch(e){}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){registration?.update().catch(()=>{});renderTimeline()}})}
setInterval(()=>{if(document.visibilityState==='visible')renderTimeline()},60000);render();
